server:
  port: 81

feign: 
  hystrix: 
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
  #      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  instance:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true     #访问路径可以显示IP地址
spring:
  application:
    name: micorservicecloud-goods-consumer-81
